In [3]:
import pandas as pd
import folium
import folium.plugins as plugins
import numpy as np
import math
from geopy import distance
import random
import time
import requests

In [4]:
pd.options.display.max_rows = 300

In [5]:
sz_car = pd.read_csv("../../data/travel_times_super_zones_driving.csv", index_col=0)
sz_non_car = pd.read_csv("../../data/travel_times_super_zones_non_car.csv", index_col=0)
zone_data = pd.read_csv("../../data/zone_coordinates_with_super_zones.csv", index_col=0)

In [6]:
def get_geojson_points(zone_data):

    all_points = []

    for index, row in zone_data.iterrows():
        
        # Define dimensions of box in grid (lon, lat) altså bortover, oppover
        if not pd.isnull(row['Super_center']):
            coordinates = [float(row['Super_center'].split(',')[0][1:]), float(row['Super_center'].split(',')[1][1:-1])]


            geo_json = {"type": "FeatureCollection",
                        "properties":{
                            #"lower_left": lower_left,
                            #"upper_right": upper_right,
                        },
                        "features":[],
                        "Number": float(row['Super_center_nr'])}

            grid_feature = {
                "type":"Feature",
                "geometry":{
                    "type":"Point",
                    "coordinates": coordinates,
                }
            }

            geo_json["features"].append(grid_feature)

            all_points.append(geo_json)

    return all_points

In [7]:
def get_geojson_super_zone_frames(zone_data):

    all_boxes = []

    for index, row in zone_data.iterrows():
        
        center = [float(row['Super_center'].split(',')[0][1:]), float(row['Super_center'].split(',')[1][1:-1])]
        
        # Define dimensions of box in grid (lon, lat) altså bortover, oppover
        if int(row['Super_center_nr']) < 48:
            
            # Define dimensions of box in grid (lon, lat) altså bortover, oppover
            lower_left = [center[0]-0.008734, center[1]-0.004537]
            upper_right = [center[0]+0.008734, center[1]+0.004537]
            upper_left = [center[0]-0.008734, center[1]+0.004537]
            lower_right = [center[0]+0.008734, center[1]-0.004537]
        
        else:
           
            # Define dimensions of box in grid (lon, lat) altså bortover, oppover
            lower_left = [center[0]-0.004367, center[1]-0.002268]
            upper_right = [center[0]+0.004367, center[1]+0.002268]
            upper_left = [center[0]-0.004367, center[1]+0.002268]
            lower_right = [center[0]+0.004367, center[1]-0.002268]
            
            
            
        # Define json coordinates for polygon
        coordinates = [
            upper_left,
            upper_right,
            lower_right,
            lower_left,
            upper_left
        ]

        geo_json = {"type": "FeatureCollection",
                    "properties":{
                        "lower_left": lower_left,
                        "upper_right": upper_right,
                    },
                    "features":[],
                    "Number": float(row['Super_center_nr'])}

        grid_feature = {
            "type":"Feature",
            "geometry":{
                "type":"Polygon",
                "coordinates": [coordinates],
            }
        }

        geo_json["features"].append(grid_feature)

        all_boxes.append(geo_json)

    return all_boxes

In [8]:
def get_geojson_grid(zone_data):
    
    all_boxes = []

    for index, row in zone_data.iterrows():
        
        # Define dimensions of box in grid (lon, lat) altså bortover, oppover
        lower_left = [float(row['Lower_left'].split(',')[0][1:]), float(row['Lower_left'].split(',')[1][1:-1])]
        upper_right = [float(row['Upper_right'].split(',')[0][1:]), float(row['Upper_right'].split(',')[1][1:-1])]
        upper_left = [lower_left[0], upper_right[1]]
        lower_right = [upper_right[0], lower_left[1]]
     
        # Define json coordinates for polygon
        coordinates = [
            upper_left,
            upper_right,
            lower_right,
            lower_left,
            upper_left
        ]

        geo_json = {"type": "FeatureCollection",
                    "properties":{
                        "lower_left": lower_left,
                        "upper_right": upper_right,
                    },
                    "features":[],
                    "Number": float(row['Zone'])}

        grid_feature = {
            "type":"Feature",
            "geometry":{
                "type":"Polygon",
                "coordinates": [coordinates],
            }
        }

        geo_json["features"].append(grid_feature)

        all_boxes.append(geo_json)

    return all_boxes
    

In [22]:
def plot_samples_on_grid(zone_data):
    
    lower_left = [59.855331, 10.601628]
    upper_right = [59.973287, 10.950989]
    
    center = [lower_left[0]+(upper_right[0]-lower_left[0])/2,lower_left[1]+(upper_right[1]-lower_left[1])/2]

    grid_size = (26,40)
    
    map = folium.Map(center, zoom_start = 10.8, zoom_snap=0.2, tiles='cartodbpositron')
    
    grid = get_geojson_grid(zone_data)
    points = get_geojson_points(zone_data)
    squares = get_geojson_super_zone_frames(zone_data)
    
    #Grid
    
    for i, geo_json in enumerate(grid):
        
        gj = folium.GeoJson(geo_json,
                style_function=lambda feature: {#'fillColor': color,
                                                'color':'darkorange',
                                                'weight': 2,
                                                'dashArray': '5, 5',
                                                'fillOpacity': 0.3}).add_to(map)
        popup_string = "Zone "+ str(int(geo_json['Number']))
        
        gj.add_child(folium.Popup(popup_string, max_width=400))
    
    #Points superzones
    '''
    for i, geo_json in enumerate(points):
        
        gj = folium.GeoJson(geo_json,
                style_function=lambda feature: {#'fillColor': color,
                                                'color':'darkorange',
                                                'weight': 5,
                                                'dashArray': '5, 5',
                                                'fillOpacity': 0.3}).add_to(map)
        popup_string = "Zone "+ str(int(geo_json['Number']))
        
        gj.add_child(folium.Popup(popup_string, max_width=400))
    '''
  
    #squares superzones
    for i, geo_json in enumerate(squares):
        
        gj = folium.GeoJson(geo_json,
                style_function=lambda feature: {#'fillColor': color,
                                                'color':'#228b21',
                                                'weight': 5,
                                                'dashArray': '5, 5',
                                                'fillOpacity': 0.0}).add_to(map)
        popup_string = "Zone "+ str(int(geo_json['Number']))
        
        gj.add_child(folium.Popup(popup_string, max_width=400))
  
    display(map)
    map.save(outfile="test.html")
    

In [23]:
plot_samples_on_grid(zone_data)

In [11]:
plot_samples_on_grid(zone_data)

In [8]:
zone_data.head(300)

Zone              Lower_left             Upper_right  \
0       1  [10.793777, 59.964213]   [10.802511, 59.96875]   
1       2  [10.785043, 59.964213]   [10.793777, 59.96875]   
2       3  [10.776308, 59.964213]   [10.785043, 59.96875]   
3       4  [10.767574, 59.964213]   [10.776309, 59.96875]   
4       5   [10.75884, 59.964213]   [10.767574, 59.96875]   
5       6  [10.750106, 59.964213]    [10.75884, 59.96875]   
6       7  [10.732638, 59.964213]   [10.741372, 59.96875]   
7       8  [10.723904, 59.964213]   [10.732638, 59.96875]   
8       9  [10.793777, 59.959677]  [10.802511, 59.964213]   
9      10  [10.785043, 59.959677]  [10.793777, 59.964213]   
10     11  [10.776308, 59.959677]  [10.785043, 59.964213]   
11     12   [10.75884, 59.959677]  [10.767574, 59.964213]   
12     13  [10.750106, 59.959677]   [10.75884, 59.964213]   
13     14  [10.741372, 59.959677]  [10.750106, 59.964213]   
14     15  [10.732638, 59.959677]  [10.741372, 59.964213]   
15     16  [10.723904, 59.959677]  [10.732638, 59.964213]   
16     17   [10.793777, 59.95514]  [10.802511, 59.959677]   
17     18   [10.785043, 59.95514]  [10.793777, 59.959677]   
18     19   [10.776308, 59.95514]  [10.785043, 59.959677]   
19     20    [10.75884, 59.95514]  [10.767574, 59.959677]   
20     21   [10.750106, 59.95514]   [10.75884, 59.959677]   
21     22   [10.741372, 59.95514]  [10.750106, 59.959677]   
22     23   [10.732638, 59.95514]  [10.741372, 59.959677]   
23     24   [10.723904, 59.95514]  [10.732638, 59.959677]   
24     25    [10.71517, 59.95514]  [10.723904, 59.959677]   
25     26  [10.793777, 59.950603]   [10.802511, 59.95514]   
26     27  [10.785043, 59.950603]   [10.793777, 59.95514]   
27     28  [10.776308, 59.950603]   [10.785043, 59.95514]   
28     29  [10.767574, 59.950603]   [10.776309, 59.95514]   
29     30   [10.75884, 59.950603]   [10.767574, 59.95514]   
30     31  [10.750106, 59.950603]    [10.75884, 59.95514]   
31     32  [10.741372, 59.950603]   [10.750106, 59.95514]   
32     33  [10.732638, 59.950603]   [10.741372, 59.95514]   
33     34  [10.723904, 59.950603]   [10.732638, 59.95514]   
34     35   [10.71517, 59.950603]   [10.723904, 59.95514]   
35     36  [10.802511, 59.946066]  [10.811245, 59.950603]   
36     37  [10.793777, 59.946066]  [10.802511, 59.950603]   
37     38  [10.785043, 59.946066]  [10.793777, 59.950603]   
38     39  [10.776308, 59.946066]  [10.785043, 59.950603]   
39     40  [10.767574, 59.946066]  [10.776309, 59.950603]   
40     41   [10.75884, 59.946066]  [10.767574, 59.950603]   
41     42  [10.750106, 59.946066]   [10.75884, 59.950603]   
42     43  [10.741372, 59.946066]  [10.750106, 59.950603]   
43     44  [10.732638, 59.946066]  [10.741372, 59.950603]   
44     45  [10.723904, 59.946066]  [10.732638, 59.950603]   
45     46  [10.706436, 59.946066]   [10.71517, 59.950603]   
46     47   [10.802511, 59.94153]  [10.811245, 59.946066]   
47     48   [10.793777, 59.94153]  [10.802511, 59.946066]   
48     49   [10.785043, 59.94153]  [10.793777, 59.946066]   
49     50   [10.776308, 59.94153]  [10.785043, 59.946066]   
50     51   [10.767574, 59.94153]  [10.776309, 59.946066]   
51     52    [10.75884, 59.94153]  [10.767574, 59.946066]   
52     53   [10.750106, 59.94153]   [10.75884, 59.946066]   
53     54   [10.741372, 59.94153]  [10.750106, 59.946066]   
54     55   [10.732638, 59.94153]  [10.741372, 59.946066]   
55     56   [10.723904, 59.94153]  [10.732638, 59.946066]   
56     57    [10.71517, 59.94153]  [10.723904, 59.946066]   
57     58   [10.706436, 59.94153]   [10.71517, 59.946066]   
58     59   [10.697702, 59.94153]  [10.706436, 59.946066]   
59     60  [10.889851, 59.936993]   [10.898585, 59.94153]   
60     61  [10.828713, 59.936993]   [10.837447, 59.94153]   
61     62  [10.819979, 59.936993]   [10.828713, 59.94153]   
62     63  [10.811245, 59.936993]   [10.819979, 59.94153]   
63     64  [10.802511, 59.936993]   [10.811245, 59.94153]   
64     65  [10.793777, 59.936993]   [10.

In [9]:
sz_car.head(200)

1     2     3     4     5     6     7     8     9    10  ...   104  \
1       0   592   789   333   608   779   972   417   366   628  ...  1008   
2     588     0   405   646   338   508   730   761   481   484  ...   973   
3     801   421     0   860   413   315   579   820   572   575  ...  1064   
4     318   648   765     0   516   642   859   289   253   515  ...   895   
5     629   353   403   596     0   280   557   564   316   319  ...   808   
6     823   504   306   749   308     0   576   716   468   472  ...   960   
7    1002   829   599   926   610   612     0   893   645   691  ...  1137   
8     429   773   771   298   522   649   865     0   256   521  ...   901   
9     391   501   517   286   269   395   612   253     0   267  ...   647   
10    614   484   556   538   292   433   655   505   257     0  ...   775   
11    730   468   391   695   214   269   546   662   414   260  ...   856   
12    669   462   392   593   277   331   479   560   312   358  ...   804   
13    937   730   594   861   545   599   636   828   580   626  ...  1072   
14    752   749   766   641   517   643   860   608   395   550  ...   650   
15    818   810   826   665   577   704   921   631   455   611  ...   683   
16    599   585   601   445   352   479   696   411   236   386  ...   632   
17    688   691   763   514   499   640   828   480   331   317  ...   733   
18    784   549   500   708   324   378   655   675   427   273  ...   921   
19    826   619   548   750   434   488   659   717   469   515  ...   961   
20    961   754   618   885   569   623   660   852   604   650  ...  1096   
21   1090   883   728  1013   698   741   701   981   733   720  ...  1224   
22   1133   926   790  1056   741   795   831  1024   775   822  ...  1168   
23    576   573   590   466   341   467   684   432   219   375  ...   504   
24    735   721   738   582   489   615   832   548   373   523  ...   644   
25    859   845   861   705   612   739   956   671   496   646  ...   862   
26    942   708   658   723   482   536   813   689   585   431  ...   883   
27    987   780   709   910   595   649   764   878   630   581  ...   968   
28    987   780   644   911   595   649   686   878   630   676  ...  1122   
29   1224  1017   881  1148   832   886   896  1115   867   827  ...   960   
30   1210  1003   867  1134   818   872   909  1101   853   899  ...   826   
31    885   882   899   775   650   776   993   741   528   683  ...   546   
32    931   928   945   887   696   822  1039   853   574   729  ...   607   
33   1014  1000  1016   860   767   894  1111   826   651   801  ...   705   
34    880   866   882   726   633   759   976   692   517   667  ...   752   
35   1242  1008   959  1023   782   836  1124   989   885   731  ...   805   
36   1202   995   859  1125   810   864   900  1093   844   890  ...   822   
37   1116   909   773  1039   724   778   814  1007   758   805  ...   899   
38   1374  1167  1150  1222   973  1028  1151  1188  1017   923  ...   819   
39    915   912   929   804   680   806  1023   771   558   713  ...   491   
40    806   804   820   696   571   697   914   662   449   605  ...   534   
41   1109  1106  1151  1035   874  1028  1217  1001   752   924  ...   632   
42    961   958   975   850   726   852  1069   816   603   759  ...   321   
43    987   984  1001   876   752   878  1095   842   629   785  ...   414   
44   1010  1008  1024   900   775   902  1119   866   653   809  ...   281   
45   1161  1158  1175  1050   926  1052  1269  1016   804   959  ...   431   
46   1034  1032  1048   924   799   926  1143   890   677   833  ...   139   
47   1260  1257  1274  1150  1025  1151  1368  1116   903  1058  ...   365   
48    309   392   590   368   409   579   801   483   366   555  ...  1007   
49    373   328   526   432   344   515   736   547   430   491  ...   980   
50    249   433   631   308   449   620   844   423   306   568  ...   948   
51    634   254   193   692   

In [10]:
sz_non_car.head()

1    2     3     4    5    6     7     8     9   10  ...   104   105  \
1     0  824  1281   283  644  830  1251   589   460  664  ...  2884  3239   
2   896    0   451   775  238  381   579  1027   792  490  ...  3073  3429   
3  1304  534     0  1182  531  348   225  1434  1137  773  ...  3185  2806   
4   401  847  1402     0  667  881  1303   322   236  503  ...  2580  2936   
5   994  485   805   872    0  297   719  1306   636  335  ...  2918  2787   

    106   107   108   109   110   111   112   113  
1  3359  3303  2715  3364  3425  3360  3604  3612  
2  2941  2663  2573  3554  2784  3549  2964  2972  
3  3020  2722  2652  2849  2780  2905  3040  3048  
4  3056  3000  2338  3061  3121  3057  3301  3309  
5  2785  2507  2417  2830  2629  2886  2808  2816  

[5 rows x 113 columns]

### API and function for getting travel times from google

In [11]:
mathiasAPI = "AIzaSyCt4jyjtrlCShT2W9cneZUI3SkHQlWF3SI"

In [12]:
def cleanCalculateTravelTimeMatrixFromCoordVector(coordVector, transportType, apikey, writeToFile):
    numberOfCoordinates = len(coordVector)
    secondMatrix = [[0 for i in range(numberOfCoordinates)] for j in range(numberOfCoordinates)]
    numberOfQueries = 0
    totalQueries = 0
    for i in range(numberOfCoordinates):
        origin = makeStringListFromCoordinateVector([coordVector[i]])
        for j in range(numberOfCoordinates):
            if(numberOfQueries > 99):
                time.sleep(1)
                numberOfQueries = 0
            destination = makeStringListFromCoordinateVector([coordVector[j]])
            url = "https://maps.googleapis.com/maps/api/distancematrix/json?origins=" + origin + "&destinations=" + destination + "&key=" + apikey + "&mode=" + transportType
            data = requests.get(url).json()
            #print(data)
            if ("error_message" in data.keys()):
                print(data["error_message"])
                return secondMatrix
            # retrieve travel time in seconds from json object
            seconds = data["rows"][0]["elements"][0]["duration"]["value"]
            # add travel time to matrix
            secondMatrix[i][j] = seconds
            numberOfQueries += 1
            totalQueries += 1
            #print(totalQueries)
    if(writeToFile):
        writeMatrixToFile(secondMatrix, transportType)
        print(secondMatrix)
    return secondMatrix

def writeMatrixToFile(matrix, transportType):
    if transportType == "":
        transportType = "car"
    fil = open("travelTimes_SuperZones_" + transportType + ".txt", "w")
    writeString = ""
    for row in matrix:
        for elem in row:
            writeString += str(elem) + " "
        writeString = writeString[:-1] + "\n"
    fil.write(writeString[:-1])
    fil.close()


def makeStringListFromCoordinateVector(coordVector):
    ret = ""
    for coor in coordVector:
        ret += str(coor[0]) + "," + str(coor[1]) + "|"
    ret = ret[:-1]
    return ret


def run(coordVector, transportType, writeToFile):
    apikey = mathiasAPI
    #print("number of coordinates", len(coordVector))
    return cleanCalculateTravelTimeMatrixFromCoordVector(coordVector, transportType, apikey, writeToFile)

### Travel times car, only super zone values

In [13]:
travel_times_car = np.zeros([254,254], dtype=int)

In [14]:
for row in range(254):
     for col in range(254):
            super_zone_row = int(zone_data.at[row, 'Super_center_nr'])
            super_zone_col = str(int(zone_data.at[col, 'Super_center_nr']))
            travel_times_car[row][col] = sz_car.at[super_zone_row, super_zone_col]

In [15]:
travel_times_car

array([[   0,    0,  308, ..., 1248, 1248, 1332],
       [   0,    0,  308, ..., 1248, 1248, 1332],
       [ 309,  309,    0, ..., 1248, 1248, 1331],
       ...,
       [1260, 1260, 1258, ...,    0,    0,  287],
       [1260, 1260, 1258, ...,    0,    0,  287],
       [1358, 1358, 1356, ...,  308,  308,    0]])

In [16]:
zones = [i for i in range(1, 255)]

In [17]:
travel_times_car_df = pd.DataFrame(travel_times_car, columns=zones, index = zones)

In [18]:
travel_times_car_df

1     2     3     4     5     6     7     8     9     10   ...   245  \
1       0     0   308   376   592   592   789   789     0     0  ...  1026   
2       0     0   308   376   592   592   789   789     0     0  ...  1026   
3     309   309     0   177   392   392   590   590   309   309  ...  1025   
4     373   373   173     0   328   328   526   526   373   373  ...   997   
5     588   588   388   307     0     0   405   405   588   588  ...   991   
6     588   588   388   307     0     0   405   405   588   588  ...   991   
7     801   801   602   520   421   421     0     0   801   801  ...  1081   
8     801   801   602   520   421   421     0     0   801   801  ...  1081   
9       0     0   308   376   592   592   789   789     0     0  ...  1026   
10      0     0   308   376   592   592   789   789     0     0  ...  1026   
11    249   249   149   217   433   433   631   631   249   249  ...   965   
12    588   588   388   307     0     0   405   405   588   588  ...   991   
13    588   588   388   307     0     0   405   405   588   588  ...   991   
14    634   634   434   353   254   254   193   193   634   634  ...   914   
15    801   801   602   520   421   421     0     0   801   801  ...  1081   
16    801   801   602   520   421   421     0     0   801   801  ...  1081   
17    318   318   365   433   648   648   765   765   318   318  ...   912   
18    318   318   365   433   648   648   765   765   318   318  ...   912   
19    301   301   254   322   537   537   735   735   301   301  ...   907   
20    629   629   429   348   353   353   403   403   629   629  ...   825   
21    629   629   429   348   353   353   403   403   629   629  ...   825   
22    823   823   624   542   504   504   306   306   823   823  ...   978   
23    823   823   624   542   504   504   306   306   823   823  ...   978   
24   1002  1002   859   777   829   829   599   599  1002  1002  ...  1155   
25   1002  1002   859   777   829   829   599   599  1002  1002  ...  1155   
26    318   318   365   433   648   648   765   765   318   318  ...   912   
27    318   318   365   433   648   648   765   765   318   318  ...   912   
28    336   336   335   402   618   618   690   690   336   336  ...   838   
29    475   475   428   445   463   463   480   480   475   475  ...   854   
30    629   629   429   348   353   353   403   403   629   629  ...   825   
31    629   629   429   348   353   353   403   403   629   629  ...   825   
32    823   823   624   542   504   504   306   306   823   823  ...   978   
33    823   823   624   542   504   504   306   306   823   823  ...   978   
34   1002  1002   859   777   829   829   599   599  1002  1002  ...  1155   
35   1002  1002   859   777   829   829   599   599  1002  1002  ...  1155   
36    429   429   490   558   773   773   771   771   429   429  ...   919   
37    429   429   490   558   773   773   771   771   429   429  ...   919   
38    391   391   389   457   501   501   517   517   391   391  ...   665   
39    391   391   389   457   501   501   517   517   391   391  ...   665   
40    614   614   547   466   484   484   556   556   614   614  ...   792   
41    614   614   547   466   484   484   556   556   614   614  ...   792   
42    730   730   531   449   468   468   391   391   730   730  ...   874   
43    730   730   531   449   468   468   391   391   730   730  ...   874   
44    669   669   525   444   462   462   392   392   669   669  ...   821   
45    669   669   525   444   462   462   392   392   669   669  ...   821   
46    762   762   618   537   555   555   419   419   762   762  ...   914   
47    429   429   490   558   773   773   771   771   429   429  ...   919   
48    429   429   490   558   773   773   771   771   429   429  ...   919   
49    391   391   389   457   501   501   517   517   391   391  ...   665   
50    391   391   389   457   501   501   517   517   391   391  ...   665   
51    614   614   547   466 

for eksempel sone 1 til sone 19. Ser at supersone tid er 355. Henter distance fra supersone til super sone. henter distance fra ekte sone til ekte sone. Får tid per km fra super sone til supersone. Ganger denne med avstand fra sone til sone. setter inn reistetid

### Travel times scaled by distance per time, except internally in super zones

In [19]:
real_travel_times = np.zeros([254,254], dtype=int)
for row in range(254):
    for col in range(254):
        
        if (travel_times_car[row][col] != 0):
            center_coord_row = str(zone_data.at[row, 'Center'])
            center_coord_row = [float(center_coord_row[1:-1].split(', ')[1]), float(center_coord_row[1:-1].split(', ')[0])]

            super_center_coord_row = str(zone_data.at[row, 'Super_center'])
            super_center_coord_row = [float(super_center_coord_row[1:-1].split(', ')[1]), float(super_center_coord_row[1:-1].split(', ')[0])]



            center_coord_col = str(zone_data.at[col, 'Center'])
            center_coord_col = [float(center_coord_col[1:-1].split(', ')[1]), float(center_coord_col[1:-1].split(', ')[0])]

            super_center_coord_col = str(zone_data.at[col, 'Super_center'])
            super_center_coord_col = [float(super_center_coord_col[1:-1].split(', ')[1]), float(super_center_coord_col[1:-1].split(', ')[0])]

            distance_super = float(distance.distance(super_center_coord_row, super_center_coord_col).km)
            distance_real = float(distance.distance(center_coord_row, center_coord_col).km)


            travel_time_super = travel_times_car[row,col]

            time_per_km = travel_time_super/distance_super
            travel_time = time_per_km*distance_real
            
            real_travel_times[row][col] = travel_time


In [20]:
real_travel_times

array([[   0,    0,  388, ..., 1304, 1300, 1361],
       [   0,    0,  194, ..., 1310, 1304, 1362],
       [ 389,  194,    0, ..., 1279, 1271, 1331],
       ...,
       [1316, 1322, 1289, ...,    0,    0,  361],
       [1313, 1316, 1281, ...,    0,    0,  180],
       [1387, 1389, 1356, ...,  388,  194,    0]])

### Filling the internal travel times within super zones with calls to google API

In [40]:
# Ikke kjør, koster penger
#for szone in range(47):
    zones = np.array(zone_data.loc[(zone_data.Super_center_nr == float(szone+1)), 'Zone'])
    #print(zones)
    
    
    coordinate_string = ""
    for i in range(4):

        coordinates_string = str(zone_data.loc[zone_data['Zone'] == zones[i], 'Center'].iloc[0])
        coordinates_string = coordinates_string[1:-1]
        long, lat = coordinates_string.split(", ")
        coordinate_string += lat + "," + long + "|"

    coordinate_string = coordinate_string[:-1]

    
    coordvector =[]
    coords = coordinate_string.split("|")
    for i in range(4):
        coordinates = coords[i].split(",")
        coordinates[0] = float(coordinates[0])
        coordinates[1] = float(coordinates[1])
        coordvector.append(coordinates)
    
    #print(coordvector)
    
    internal_traveltimes = cleanCalculateTravelTimeMatrixFromCoordVector(coordvector, "driving", mathiasAPI, False)
    #print(internal_traveltimes)
    
    
    real_travel_times[zones[0]-1][zones[1]-1] = internal_traveltimes[0][1]
    real_travel_times[zones[0]-1][zones[2]-1] = internal_traveltimes[0][2]
    real_travel_times[zones[0]-1][zones[3]-1] = internal_traveltimes[0][3]
    real_travel_times[zones[1]-1][zones[0]-1] = internal_traveltimes[1][0]
    real_travel_times[zones[1]-1][zones[2]-1] = internal_traveltimes[1][2]
    real_travel_times[zones[1]-1][zones[3]-1] = internal_traveltimes[1][3]
    real_travel_times[zones[2]-1][zones[0]-1] = internal_traveltimes[2][0]
    real_travel_times[zones[2]-1][zones[1]-1] = internal_traveltimes[2][1]
    real_travel_times[zones[2]-1][zones[3]-1] = internal_traveltimes[2][3]
    real_travel_times[zones[3]-1][zones[0]-1] = internal_traveltimes[3][0]
    real_travel_times[zones[3]-1][zones[1]-1] = internal_traveltimes[3][1]
    real_travel_times[zones[3]-1][zones[2]-1] = internal_traveltimes[3][2]

[ 1  2  9 10]
[[59.966482, 10.798144], [59.966482, 10.78941], [59.961945, 10.798144], [59.961945, 10.78941]]
[[0, 365, 170, 256], [344, 0, 422, 135], [146, 441, 0, 332], [272, 152, 350, 0]]
[ 5  6 12 13]
[[59.966482, 10.763207], [59.966482, 10.754473], [59.961945, 10.763207], [59.961945, 10.754473]]
[[0, 246, 179, 300], [264, 0, 262, 240], [195, 253, 0, 261], [304, 225, 264, 0]]
[ 7  8 15 16]
[[59.966482, 10.737005], [59.966482, 10.728271], [59.961945, 10.737005], [59.961945, 10.728271]]
[[0, 428, 230, 444], [410, 0, 208, 383], [202, 198, 0, 214], [418, 386, 216, 0]]
[17 18 26 27]
[[59.957408, 10.798144], [59.957408, 10.78941], [59.952872, 10.798144], [59.952872, 10.78941]]
[[0, 214, 51, 155], [225, 0, 170, 146], [55, 163, 0, 104], [162, 147, 107, 0]]
[20 21 30 31]
[[59.957408, 10.763207], [59.957408, 10.754473], [59.952872, 10.763207], [59.952872, 10.754473]]
[[0, 291, 270, 319], [258, 0, 283, 332], [249, 286, 0, 237], [309, 346, 245, 0]]
[22 23 32 33]
[[59.957408, 10.745739], [59.957

[[0, 224, 514, 541], [216, 0, 290, 317], [507, 291, 0, 202], [547, 331, 204, 0]]
[229 230 234 235]
[[59.88482, 10.806878], [59.88482, 10.798144], [59.880283, 10.806878], [59.880283, 10.798144]]
[[0, 339, 180, 252], [319, 0, 225, 162], [172, 229, 0, 96], [253, 157, 94, 0]]
[231 232 236 237]
[[59.88482, 10.78941], [59.88482, 10.780676], [59.880283, 10.78941], [59.880283, 10.780676]]
[[0, 157, 188, 289], [170, 0, 167, 213], [201, 184, 0, 214], [295, 205, 209, 0]]
[238 239 244 245]
[[59.875746, 10.824346], [59.875746, 10.815612], [59.87121, 10.824346], [59.87121, 10.815612]]
[[0, 109, 219, 270], [319, 0, 219, 195], [358, 175, 0, 178], [403, 193, 246, 0]]
[249 250 252 253]
[[59.866673, 10.815612], [59.866673, 10.806878], [59.862136, 10.815612], [59.862136, 10.806878]]
[[0, 252, 193, 314], [247, 0, 236, 181], [167, 225, 0, 295], [317, 182, 149, 0]]


In [41]:
real_travel_times

array([[   0,  365,  388, ..., 1304, 1300, 1361],
       [ 344,    0,  194, ..., 1310, 1304, 1362],
       [ 389,  194,    0, ..., 1279, 1271, 1331],
       ...,
       [1316, 1322, 1289, ...,    0,  295,  361],
       [1313, 1316, 1281, ...,  149,    0,  180],
       [1387, 1389, 1356, ...,  388,  194,    0]])

### Creating dataframe and saving to csv

In [42]:
zones = [i for i in range(1, 255)]
real_travel_times_car_df = pd.DataFrame(real_travel_times, columns=zones, index=zones)

In [43]:
real_travel_times_car_df.head(300)

1     2     3     4     5     6     7     8     9     10   ...   245  \
1       0   365   388   441   591   739   788   901   170   256  ...  1070   
2     344     0   194   294   443   591   676   788   422   135  ...  1076   
3     389   194     0   177   307   460   533   640   438   280  ...  1044   
4     438   292   173     0   206   413   464   580   463   329  ...  1014   
5     587   440   303   193     0   246   404   539   607   466  ...  1022   
6     734   587   455   386   264     0   269   404   750   607  ...  1035   
7     800   686   544   459   420   280     0   428   809   696  ...  1106   
8     915   800   653   573   561   420   410     0   923   809  ...  1125   
9     146   441   437   467   611   755   797   909     0   332  ...  1020   
10    272   152   279   331   469   611   686   797   350     0  ...  1026   
11    353   225   149   216   381   538   583   695   313   156  ...   983   
12    607   466   342   278   195   253   428   557   588   441  ...   977   
13    750   607   482   435   304   225   304   428   735   588  ...   991   
14    698   585   434   353   360   230   175   273   688   573  ...   926   
15    809   696   556   474   445   316   202   198   801   686  ...  1061   
16    923   809   663   586   579   445   418   386   915   801  ...  1081   
17    318   353   351   438   647   778   764   865   159   221  ...   955   
18    353   318   280   346   524   647   665   764   221   159  ...   961   
19    401   320   254   322   525   665   696   816   313   200  ...   925   
20    628   509   343   267   353   392   402   497   576   443  ...   852   
21    755   628   434   334   392   353   318   402   712   576  ...   865   
22    822   701   541   453   504   402   306   383   789   662  ...  1003   
23    946   822   650   560   638   504   275   306   917   789  ...  1022   
24   1001   885   779   691   828   670   599   539   978   858  ...  1177   
25   1119  1001   896   811   995   828   749   599  1098   978  ...  1202   
26    477   501   450   519   728   846   802   899   317   353  ...   905   
27    501   477   398   444   621   728   708   802   353   317  ...   912   
28    414   366   335   402   634   741   668   766   323   258  ...   855   
29    570   487   428   445   505   571   468   544   481   380  ...   870   
30    707   603   440   379   529   556   477   559   629   509  ...   811   
31    822   707   514   429   556   529   408   477   755   629  ...   825   
32    876   763   608   537   646   571   434   491   823   701  ...   958   
33    993   876   707   630   756   646   413   434   946   823  ...   978   
34   1040   928   829   752   932   794   850   809  1002   885  ...  1128   
35   1154  1040   940   863  1083   932   962   850  1119  1002  ...  1155   
36    428   463   473   551   772   867   770   847   328   371  ...   970   
37    417   428   426   489   685   772   696   770   312   328  ...   975   
38    390   380   353   429   500   564   516   576   299   285  ...   696   
39    422   390   343   397   450   500   460   516   339   299  ...   704   
40    613   552   476   411   483   522   555   626   518   443  ...   822   
41    691   613   513   423   470   483   493   555   607   518  ...   835   
42    729   647   465   390   467   454   390   434   661   569  ...   899   
43    819   729   524   434   505   467   362   390   759   661  ...   918   
44    668   599   472   394   461   415   392   403   629   555  ...   838   
45    740   668   530   444   520   461   403   392   705   629  ...   858   
46    811   742   618   537   614   547   486   437   784   713  ...   919   
47    530   558   554   626   856   943   815   888   429   463  ...   914   
48    521   530   514   572   778   856   745   815   417   429  ...   919   
49    483   475   437   518   586   640   561   617   391   380  ...   656   
50    509   483   429   492   543   586   510   561   422   391  ...   665   
51    718   666   589   514 

In [44]:
#real_travel_times_car_df.to_csv("../../data/travel_times_car_all_zones.csv")

### Doing everything again, this time for non car travel times

In [21]:
travel_times_non_car = np.zeros([254,254], dtype=int)

In [22]:
for row in range(254):
     for col in range(254):
            super_zone_row = int(zone_data.at[row, 'Super_center_nr'])
            super_zone_col = str(int(zone_data.at[col, 'Super_center_nr']))
            travel_times_non_car[row][col] = sz_non_car.at[super_zone_row, super_zone_col]

In [23]:
travel_times_non_car

array([[   0,    0,  321, ..., 3474, 3474, 3612],
       [   0,    0,  321, ..., 3474, 3474, 3612],
       [ 738,  738,    0, ..., 3680, 3680, 3021],
       ...,
       [3758, 3758, 3079, ...,    0,    0,  278],
       [3758, 3758, 3079, ...,    0,    0,  278],
       [3674, 3674, 3259, ...,  501,  501,    0]])

### Travel times scaled by distance per time, except internally in super zones

In [24]:
real_travel_times_non_car = np.zeros([254,254], dtype=int)
for row in range(254):
    for col in range(254):
        
        if (travel_times_non_car[row][col] != 0):
            center_coord_row = str(zone_data.at[row, 'Center'])
            center_coord_row = [float(center_coord_row[1:-1].split(', ')[1]), float(center_coord_row[1:-1].split(', ')[0])]

            super_center_coord_row = str(zone_data.at[row, 'Super_center'])
            super_center_coord_row = [float(super_center_coord_row[1:-1].split(', ')[1]), float(super_center_coord_row[1:-1].split(', ')[0])]


            center_coord_col = str(zone_data.at[col, 'Center'])
            center_coord_col = [float(center_coord_col[1:-1].split(', ')[1]), float(center_coord_col[1:-1].split(', ')[0])]

            super_center_coord_col = str(zone_data.at[col, 'Super_center'])
            super_center_coord_col = [float(super_center_coord_col[1:-1].split(', ')[1]), float(super_center_coord_col[1:-1].split(', ')[0])]

            distance_super = float(distance.distance(super_center_coord_row, super_center_coord_col).km)
            distance_real = float(distance.distance(center_coord_row, center_coord_col).km)


            travel_time_super = travel_times_non_car[row,col]

            time_per_km = travel_time_super/distance_super
            travel_time = time_per_km*distance_real
            
            real_travel_times_non_car[row][col] = travel_time


In [25]:
real_travel_times_non_car

array([[   0,    0,  404, ..., 3630, 3621, 3691],
       [   0,    0,  202, ..., 3646, 3630, 3694],
       [ 930,  465,    0, ..., 3772, 3749, 3021],
       ...,
       [3927, 3944, 3156, ...,    0,    0,  350],
       [3917, 3927, 3137, ...,    0,    0,  175],
       [3754, 3758, 3259, ...,  631,  315,    0]])

### Filling the internal travel times within super zones with calls to google API

In [26]:
# Ikke kjør, koster penger
for szone in range(47):
    zones = np.array(zone_data.loc[(zone_data.Super_center_nr == float(szone+1)), 'Zone'])
    #print(zones)
    
    
    coordinate_string = ""
    for i in range(4):

        coordinates_string = str(zone_data.loc[zone_data['Zone'] == zones[i], 'Center'].iloc[0])
        coordinates_string = coordinates_string[1:-1]
        long, lat = coordinates_string.split(", ")
        coordinate_string += lat + "," + long + "|"

    coordinate_string = coordinate_string[:-1]

    
    coordvector =[]
    coords = coordinate_string.split("|")
    for i in range(4):
        coordinates = coords[i].split(",")
        coordinates[0] = float(coordinates[0])
        coordinates[1] = float(coordinates[1])
        coordvector.append(coordinates)
    
    #print(coordvector)
    
    # internal_traveltimes_bike = cleanCalculateTravelTimeMatrixFromCoordVector(coordvector, "bicycling", mathiasAPI, False)
    # internal_traveltimes_transit = cleanCalculateTravelTimeMatrixFromCoordVector(coordvector, "transit", mathiasAPI, False)

    #print(internal_traveltimes)
    
    real_travel_times_non_car[zones[0]-1][zones[1]-1] = min(internal_traveltimes_bike[0][1],internal_traveltimes_transit[0][1])
    real_travel_times_non_car[zones[0]-1][zones[2]-1] = min(internal_traveltimes_bike[0][2],internal_traveltimes_transit[0][2])
    real_travel_times_non_car[zones[0]-1][zones[3]-1] = min(internal_traveltimes_bike[0][3],internal_traveltimes_transit[0][3])
    real_travel_times_non_car[zones[1]-1][zones[0]-1] = min(internal_traveltimes_bike[1][0],internal_traveltimes_transit[1][0])
    real_travel_times_non_car[zones[1]-1][zones[2]-1] = min(internal_traveltimes_bike[1][2],internal_traveltimes_transit[1][2])
    real_travel_times_non_car[zones[1]-1][zones[3]-1] = min(internal_traveltimes_bike[1][3],internal_traveltimes_transit[1][3])
    real_travel_times_non_car[zones[2]-1][zones[0]-1] = min(internal_traveltimes_bike[2][0],internal_traveltimes_transit[2][0])
    real_travel_times_non_car[zones[2]-1][zones[1]-1] = min(internal_traveltimes_bike[2][1],internal_traveltimes_transit[2][1])
    real_travel_times_non_car[zones[2]-1][zones[3]-1] = min(internal_traveltimes_bike[2][3],internal_traveltimes_transit[2][3])
    real_travel_times_non_car[zones[3]-1][zones[0]-1] = min(internal_traveltimes_bike[3][0],internal_traveltimes_transit[3][0])
    real_travel_times_non_car[zones[3]-1][zones[1]-1] = min(internal_traveltimes_bike[3][1],internal_traveltimes_transit[3][1])
    real_travel_times_non_car[zones[3]-1][zones[2]-1] = min(internal_traveltimes_bike[3][2],internal_traveltimes_transit[3][2])

In [27]:
real_travel_times_non_car

array([[   0,  289,  404, ..., 3630, 3621, 3691],
       [ 656,    0,  202, ..., 3646, 3630, 3694],
       [ 930,  465,    0, ..., 3772, 3749, 3021],
       ...,
       [3927, 3944, 3156, ...,    0,  251,  350],
       [3917, 3927, 3137, ...,  253,    0,  175],
       [3754, 3758, 3259, ...,  631,  315,    0]])

### Creating dataframe and saving to csv

In [28]:
zones = [i for i in range(1, 255)]
real_travel_times_non_car_df = pd.DataFrame(real_travel_times_non_car, columns=zones, index=zones)

In [29]:
real_travel_times_non_car_df.head(300)

1     2     3     4     5     6     7     8     9     10   ...   245  \
1       0   289   404   516   823  1029  1280  1463   250   247  ...  3466   
2     656     0   202   344   617   823  1097  1280   623   132  ...  3484   
3     930   465     0   231   608   912   970  1164  1047   669  ...  3593   
4     927   618   191     0   351   703   892  1115   980   696  ...  3599   
5     895   671   347   200     0   375   450   601   925   710  ...  3622   
6    1119   895   521   400   258     0   300   450  1143   925  ...  3668   
7    1303  1117   853   690   533   355     0   206  1318  1134  ...  3212   
8    1490  1303  1024   863   711   533   376     0  1502  1318  ...  3266   
9     265   455   455   546   851  1051  1294  1476     0   414  ...  3302   
10    636    86   291   388   653   851  1114  1294   535     0  ...  3322   
11    769   491   222   341   639   901  1092  1302   683   341  ...  3335   
12    925   710   391   288   268   230   477   621   896   672  ...  3462   
13   1143   925   551   451   432   175   338   477  1120   896  ...  3511   
14   1097   920   635   473   302   193   241   377  1081   901  ...  3275   
15   1318  1134   871   713   564   400   359   209  1304  1117  ...  3082   
16   1502  1318  1039   881   735   564   417    89  1490  1304  ...  3139   
17    401   445   391   532   846  1017  1401  1586   200   278  ...  3161   
18    445   401   312   420   685   846  1219  1401   278   200  ...  3181   
19    624   498   257   419   658   833  1194  1400   488   312  ...  3238   
20    993   804   463   448   485   538   804   994   911   700  ...  3223   
21   1194   993   586   561   538   485   635   804  1126   911  ...  3272   
22   1490  1271   933   835   830   663   764   956  1430  1199  ...  3320   
23   1714  1490  1121  1032  1050   830   688   764  1662  1430  ...  3382   
24   1588  1403   963   905   857   694   400   360  1551  1360  ...  3288   
25   1775  1588  1107  1061  1030   857   500   400  1741  1551  ...  3358   
26    601   631   502   631   952  1106  1470  1648   400   445  ...  2996   
27    631   601   443   540   812   952  1297  1470   445   400  ...  3018   
28    682   603   385   547   822   961  1315  1509   532   425  ...  3124   
29    955   817   562   657   931  1054  1124  1307   806   636  ...  3081   
30   1117   953   594   637   727   764   953  1118   994   804  ...  3068   
31   1299  1117   694   721   764   727   815   953  1194   994  ...  3120   
32   1587  1382  1049   990  1065   940  1084  1227  1491  1271  ...  3171   
33   1798  1587  1220  1161  1245  1065  1032  1084  1714  1491  ...  3236   
34   1650  1472  1025   984   964   822   567   540  1589  1403  ...  3151   
35   1830  1650  1162  1130  1121   964   642   567  1775  1589  ...  3225   
36    735   794   642   774  1345  1511  1516  1668   563   638  ...  2852   
37    715   735   577   687  1193  1345  1369  1516   536   563  ...  2866   
38    913   888   700   883  1093  1231  1415  1579   700   666  ...  3028   
39    986   913   680   818   983  1093  1260  1415   792   700  ...  3062   
40   1322  1189   790   873  1093  1180  1296  1462  1117   955  ...  3064   
41   1489  1322   853   898  1063  1093  1151  1296  1310  1117  ...  3114   
42   1366  1212   835   897  1024   996  1058  1177  1239  1066  ...  3260   
43   1534  1366   940   998  1106  1024   981  1058  1422  1239  ...  3328   
44   1614  1447  1066  1012  1136  1022   547   562  1520  1341  ...  2466   
45   1788  1614  1197  1141  1280  1136   562   547  1703  1520  ...  2525   
46   2103  1925  1560  1541  1388  1236   980   881  2035  1850  ...  2739   
47    910   958   751   880  1492  1642  1604  1748   736   794  ...  2685   
48    894   910   696   805  1356  1492  1466  1604   715   736  ...  2700   
49   1131  1110   866  1065  1280  1399  1539  1690   914   888  ...  2855   
50   1190  1131   850  1012  1187  1280  1397  1539   986   914  ...  2891   
51   1547  1435   978  1091 

In [30]:
#real_travel_times_non_car_df.to_csv("../../data/travel_times_non_car_all_zones.csv")